# Shadowrocket: 2026-05-29 11:51:56
[General]
tun-excluded-routes = 100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.88.99.0/24,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = false
dns-fallback-system = true
dns-direct-fallback-proxy = true
fallback-dns-server = system
hijack-dns = :53
skip-proxy = 172.16.0.0/12,localhost,*.local,captive.apple.com
always-real-ip = *
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/ctUvKU28GMKPguvr/configs/refs/heads/main/SR/Paysera.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/ctUvKU28GMKPguvr/configs/refs/heads/main/SR/NP_DOMAIN.txt,НОВАЯ 1
RULE-SET,https://raw.githubusercontent.com/ctUvKU28GMKPguvr/configs/refs/heads/main/SR/work.txt,H23-H24
DOMAIN-SUFFIX,ru,НОВАЯ 1
DOMAIN-SUFFIX,su,НОВАЯ 1
DOMAIN-SUFFIX,xn--p1ai,НОВАЯ 1
DOMAIN-SUFFIX,by,НОВАЯ 1
DOMAIN-SUFFIX,novofon.com,НОВАЯ 1
IP-CIDR,37.139.38.0/24,НОВАЯ 1
DOMAIN-SUFFIX,okko.tv,НОВАЯ 1
DOMAIN-SUFFIX,more.tv,НОВАЯ 1
DOMAIN-SUFFIX,pobeda.aero,НОВАЯ 1
DOMAIN-SUFFIX,premier.one,НОВАЯ 1
DOMAIN,api.ipify.org,НОВАЯ 1
DOMAIN,icanhazip.com,НОВАЯ 1
DOMAIN,ifconfig.me,НОВАЯ 1
DOMAIN,ifconfig.io,НОВАЯ 1
DOMAIN,httpbin.org,НОВАЯ 1
DOMAIN,ipwho.is,DIRECT
FINAL,DIRECT
